; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	dscal_
EXTRN	_fltused:DWORD
; Function compile flags: /Ogtp
;	COMDAT dscal_
_TEXT	SEGMENT
n$ = 8
sa$ = 16
sx$ = 24
incx$ = 32
dscal_	PROC						; COMDAT
; File c:\users\brian c. becker\downloads\liblinear-1.7\liblinear-1.7\blas\dscal.c
; Line 15
	movsxd	r10, DWORD PTR [rcx]
; Line 16
	movsxd	rax, DWORD PTR [r9]
; Line 17
	movsdx	xmm2, QWORD PTR [rdx]
; Line 19
	test	r10d, r10d
	jle	$LN25@dscal_
	test	eax, eax
	jle	$LN25@dscal_
; Line 24
	xor	ecx, ecx
	cmp	eax, 1
	jne	$LN11@dscal_
	lea	eax, DWORD PTR [r10-4]
	movsxd	rdx, eax
	test	eax, eax
	jle	$LN8@dscal_
	lea	rcx, QWORD PTR [rdx-1]
	mov	rax, -3689348814741910323		; cccccccccccccccdH
	lea	r9, QWORD PTR [r8+16]
	mul	rcx
	shr	rdx, 2
	inc	rdx
	lea	ecx, DWORD PTR [rdx+rdx*4]
	npad	12
$LL10@dscal_:
; Line 26
	movapd	xmm0, xmm2
; Line 27
	movapd	xmm1, xmm2
	add	r9, 40					; 00000028H
	sub	rdx, 1
	mulsd	xmm0, QWORD PTR [r9-56]
	mulsd	xmm1, QWORD PTR [r9-48]
	movsdx	QWORD PTR [r9-56], xmm0
	movsdx	QWORD PTR [r9-48], xmm1
; Line 28
	movapd	xmm0, xmm2
	mulsd	xmm0, QWORD PTR [r9-40]
; Line 29
	movapd	xmm1, xmm2
	mulsd	xmm1, QWORD PTR [r9-32]
	movsdx	QWORD PTR [r9-40], xmm0
; Line 30
	movapd	xmm0, xmm2
	mulsd	xmm0, QWORD PTR [r9-24]
	movsdx	QWORD PTR [r9-32], xmm1
	movsdx	QWORD PTR [r9-24], xmm0
	jne	SHORT $LL10@dscal_
$LN8@dscal_:
; Line 24
	movsxd	rcx, ecx
; Line 38
	cmp	rcx, r10
	jge	$LN25@dscal_
	mov	rax, r10
	sub	rax, rcx
	cmp	rax, 4
	jl	SHORT $LC22@dscal_
	mov	rdx, r10
	lea	rax, QWORD PTR [r8+rcx*8+16]
	sub	rdx, rcx
	sub	rdx, 4
	shr	rdx, 2
	inc	rdx
	lea	rcx, QWORD PTR [rcx+rdx*4]
	npad	4
$LL23@dscal_:
	movapd	xmm0, xmm2
	movapd	xmm1, xmm2
	add	rax, 32					; 00000020H
	sub	rdx, 1
	mulsd	xmm0, QWORD PTR [rax-48]
	mulsd	xmm1, QWORD PTR [rax-40]
	movsdx	QWORD PTR [rax-48], xmm0
	movsdx	QWORD PTR [rax-40], xmm1
	movapd	xmm0, xmm2
	mulsd	xmm0, QWORD PTR [rax-32]
	movapd	xmm1, xmm2
	mulsd	xmm1, QWORD PTR [rax-24]
	movsdx	QWORD PTR [rax-32], xmm0
	movsdx	QWORD PTR [rax-24], xmm1
	jne	SHORT $LL23@dscal_
$LC22@dscal_:
; Line 32
	cmp	rcx, r10
	jge	SHORT $LN25@dscal_
$LC7@dscal_:
; Line 33
	movapd	xmm0, xmm2
; Line 38
	inc	rcx
	cmp	rcx, r10
	mulsd	xmm0, QWORD PTR [r8+rcx*8-8]
	movsdx	QWORD PTR [r8+rcx*8-8], xmm0
	jl	SHORT $LC7@dscal_
; Line 43
	xor	eax, eax
; Line 44
	ret	0
$LN11@dscal_:
; Line 16
	mov	r9, rax
; Line 37
	imul	eax, r10d
	movsxd	rdx, eax
; Line 38
	test	eax, eax
	jle	SHORT $LN25@dscal_
	npad	14
$LL3@dscal_:
; Line 39
	movapd	xmm0, xmm2
	mulsd	xmm0, QWORD PTR [r8+rcx*8]
	movsdx	QWORD PTR [r8+rcx*8], xmm0
	add	rcx, r9
	cmp	rcx, rdx
	jl	SHORT $LL3@dscal_
$LN25@dscal_:
; Line 43
	xor	eax, eax
; Line 44
	ret	0
dscal_	ENDP
_TEXT	ENDS
END
